### ISSUE TITLE
Map labels are not getting rendered

### ISSUE THREAD

**Issue by Rheyo** [tobinbradley/mapbox-gl-style-editor#1]
I have used osm2pgsql to store map data into postgresql database, and t-rex tileserver to serve vector tiles out of that data. Now I have four tilesets - line, point, polygon and roads as shown in the screenshot below.
![screenshot from 2018-06-09 10-24-56](https://user-images.githubusercontent.com/34985308/41187798-dbc296a0-6bcf-11e8-93b6-c26190cae358.png)
I am doing styling of maps using your style-editor. I have used vector tiles served by t-rex as sources in the stye.json stylefile as shown below.
![screenshot from 2018-06-09 10-52-30](https://user-images.githubusercontent.com/34985308/41187993-286b746e-6bd4-11e8-9995-1bfefa6f7680.png)
I have done styling of most map parts using osm column names (from tables in the database
) instead of class in the filter. I am attaching screenshots so that there is no confusion.
![screenshot from 2018-06-09 11-16-28](https://user-images.githubusercontent.com/34985308/41188135-e61ee502-6bd6-11e8-953b-c425b3ebec4e.png)
![screenshot from 2018-06-09 11-19-46](https://user-images.githubusercontent.com/34985308/41188159-44fbad80-6bd7-11e8-81ef-1e6d5ca2db49.png)
But I am unable to show labels using the same process. Do I need to make layers in the tilesets, and if yes then how are label-layers(e.g. water-label) made. I look forward to your response, and thank you in advance for your time and consideration.

**Comment by tobinbradley** [comment]
You have a lot of moving parts where something may have gone wrong, but I can offer a few suggestions.

You do have to define label layers in your style JSON (see [symbol layer](https://www.mapbox.com/mapbox-gl-js/style-spec#layers-symbol). An example might look like this:

```javascript
{
      "id": "waterway-name",
      "type": "symbol",
      "source": "openmaptiles",
      "source-layer": "waterway",
      "minzoom": 13,
      "filter": [
        "all",
        [
          "==",
          "type",
          "LineString"
        ],
        [
          "has",
          "name"
        ]
      ],
      "layout": {
        "text-font": [
          "Noto Sans Italic"
        ],
        "text-size": 14,
        "text-field": "name",
        "text-max-width": 5,
        "text-rotation-alignment": "map",
        "symbol-placement": "line",
        "text-letter-spacing": 0.2,
        "symbol-spacing": 350
      },
      "paint": {
        "text-color": "#74aee9",
        "text-halo-width": 1.5,
        "text-halo-color": "rgba(255,255,255,0.7)"
      }
    }
```

You also have to build glyphs of whatever font your using and reference the path in your style file. Check out the [OpenMapTiles](https://openmaptiles.org/styles/) examples.

Also, I wouldn't serve base tiles this way. Too much Postgres thrashing, and there's a lot of OSM cleanup that goes into what groups like Mapbox and OpenMapTiles produce. I [build my own](https://openmaptiles.org/docs/generate/generate-openmaptiles/) OpenMapTiles tile set and host it myself.

Last thing, I'd use [maputnik](https://github.com/maputnik/editor) for tile styling. It's way better than what I built a couple of years ago.
